config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, only: %i[show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to root_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1> Create a new bookmark 📝 </h1>
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/lists/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1>WatchList has the <strong>best movies</strong> for you</h1>
    <p>Find amazing lists and add your personal favorites!</p>
    <%= link_to "Create your own list",  new_list_path, class: "btn btn-secondary"%>
  </div>
</div>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.shutterstock.com/image-illustration/watchlist-stock-market-tracker-ticker-260nw-1946563306.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Movie lists", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create your list", new_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/lists/index.html.erb
<%= render '/lists/banner' %>

<div class="container">
  <h1> Movie lists </h1>

  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key, height: 300, crop: :fill %>)">
      <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1> Create a new list 📝 </h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>);">
  <div class="container">
    <h1> <%= @list.name %> </h1>
    <br>
    <%= link_to "Add a movie",  new_list_bookmark_path(@list), class: "btn btn-secondary"%>
  </div>
</div>

<div class="container">
  <div class="cards">
    <% @list.bookmarks.each do |bookmark| %>
    <div class="card-movie">
      <img src= <%= bookmark.movie.poster_url %> alt="" style="width=400 height=300">
        <div class="card-movie-infos">
          <div>
            <h2> <%= bookmark.movie.title %> - <i class="fas fa-star"></i> <%= bookmark.movie.rating %> /10 </h2>
            <p> <%= bookmark.movie.overview %></p>
          </div>
        </div>
        <div class="footer">
          <p> <i class="fas fa-marker"></i> <%= bookmark.comment %> </p>
          <p> <%= link_to "delete", bookmark_path(bookmark), method: 'delete' %> </p>
        </div>
      </div>
    <% end %>
  </div>
</div>